### ISSUE TITLE
Option for non-loop? 

### ISSUE THREAD

**Issue by KesWalker** [lovasoa/salesman.js#10]
Is it possible to get the shortest path without having to return to the first point?

One where the last point is the furthest away so the salesman doesn't have to return all the way back to the starting point?

**Comment by lovasoa** [comment]
Hello ! No, it's not possible with the current implementation.

**Comment by KesWalker** [comment]
Does the following not acheive something similar?

    Path.prototype.randomPos = function () {
    if (this.roundTrip) {
        return 1 + Math.floor(Math.random() * (this.points.length - 1));
    } else {
        return Math.floor(Math.random() * this.points.length);
    }
    };

**Comment by lovasoa** [comment]
I don't think so. But if you open a clean pull request with good code and tests, I'll merge it :slightly_smiling_face:
